# Generated by Django 5.2.7 on 2025-11-30 22:55

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('admin_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Admin Type')),
                ('is_content_editor', models.BooleanField(default=False, verbose_name='Is Content Editor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'db_table': 'auth_user',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full legal name of the company (e.g., Rovid Smart Technology).', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='Short name or abbreviation (e.g., RovidGH).', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Company logo.', null=True, upload_to=accounts.models.get_image_upload_path)),
                ('tagline', models.CharField(blank=True, help_text='A short, catchy phrase about the company.', max_length=255)),
                ('mission', models.TextField(blank=True, help_text='Company mission statement.')),
                ('vision', models.TextField(blank=True, help_text='Company vision statement.')),
                ('values', models.JSONField(blank=True, help_text='Core values of the company.')),
                ('about_us_text', models.TextField(blank=True, help_text="Longer 'About Us' section text.")),
                ('email', models.EmailField(blank=True, help_text='General contact email address.', max_length=254)),
                ('location_description', models.CharField(blank=True, help_text="General location description (e.g., 'Accra, Ghana').", max_length=255)),
                ('mailing_address', models.TextField(blank=True, help_text='Full mailing address.')),
                ('postal_address', models.TextField(blank=True, help_text='Full postal address (if different from mailing).')),
                ('tel', models.CharField(blank=True, help_text='Main telephone number.', max_length=50)),
                ('fax', models.CharField(blank=True, help_text='Fax number.', max_length=50)),
                ('phone1', models.CharField(blank=True, help_text='Primary mobile/contact number.', max_length=50)),
                ('phone2', models.CharField(blank=True, help_text='Secondary mobile/contact number.', max_length=50)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL.', null=True)),
                ('x', models.URLField(blank=True, help_text='X (Twitter) profile URL.', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL.', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL.', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile URL.', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel URL.', null=True)),
                ('github', models.URLField(blank=True, help_text='GitHub profile/organization URL.', null=True)),
                ('google_business_profile', models.URLField(blank=True, help_text='Google Business Profile URL (e.g., Google Maps listing).', null=True)),
                ('yahoo_business_profile', models.URLField(blank=True, help_text='Yahoo Business Profile URL.', null=True)),
                ('copyright_text', models.CharField(blank=True, help_text="Text for the website footer copyright (e.g., '© 2025 Rovid Smart Technology.').", max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Company (Global Settings)',
                'constraints': [models.UniqueConstraint(fields=('id',), name='unique_company_settings')],
            },
        ),
    ]
