# Generated by Django 5.1.2 on 2025-07-13 00:54

import accounts.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Internal title for the carousel slide (e.g., 'Homepage Slide 1')", max_length=100)),
                ('image', models.ImageField(help_text='Background image for the carousel slide.', upload_to=accounts.models.get_image_upload_path)),
                ('main_text', models.CharField(help_text='The primary headline or main message on the slide.', max_length=255)),
                ('link', models.URLField(blank=True, help_text='Optional: URL this slide links to.', null=True)),
                ('text_1', models.TextField(blank=True, help_text='First line/paragraph of supporting text.')),
                ('text_2', models.TextField(blank=True, help_text='Second line/paragraph of supporting text.')),
                ('icon', models.CharField(blank=True, help_text="Optional: FontAwesome icon class (e.g., 'fa fa-play').", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which the slides appear (lower number first).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is currently active on the website.')),
            ],
            options={
                'verbose_name_plural': 'Carousels',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the client company or individual.', max_length=100, unique=True)),
                ('industry', models.CharField(blank=True, help_text="Industry of the client (e.g., 'Healthcare', 'Tech').", max_length=100)),
                ('client_logo', models.ImageField(help_text='Logo of the client.', upload_to=accounts.models.get_image_upload_path)),
                ('project_title', models.CharField(blank=True, help_text='Title of a specific project done for this client.', max_length=200)),
                ('project_link', models.URLField(blank=True, help_text='Optional: Link to the detailed project page or case study.', null=True)),
                ('display_on_homepage', models.BooleanField(default=False, help_text='Check to feature this client on the homepage.')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Subject of the message.', max_length=200)),
                ('message', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True, help_text='Date and time when the message was submitted.')),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read after reviewing the message.')),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submission_time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier for the project URL (auto-generated if left blank).', max_length=220, unique=True)),
                ('client_name', models.CharField(help_text='Name of the client for this project.', max_length=100)),
                ('client_logo', models.ImageField(blank=True, help_text="Optional: Client's logo for this specific project.", null=True, upload_to=accounts.models.get_image_upload_path)),
                ('description', models.TextField(help_text='Detailed description of the project, including scope and achievements.')),
                ('category', models.CharField(help_text="Main category of the project (e.g., 'Smart Infrastructure', 'Software').", max_length=100)),
                ('type', models.CharField(blank=True, help_text="Type of project (e.g., 'Residential', 'Commercial', 'Web Application').", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Geographical location of the project.', max_length=200)),
                ('completion_date', models.DateField(help_text='Date the project was completed.')),
                ('image1', models.ImageField(blank=True, help_text='Main image for the project.', null=True, upload_to=accounts.models.get_image_upload_path)),
                ('image2', models.ImageField(blank=True, help_text='Second image for the project.', null=True, upload_to=accounts.models.get_image_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-completion_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the service (e.g., 'Building Management Systems').", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier for the service URL (auto-generated if left blank).', max_length=120, unique=True)),
                ('image', models.ImageField(help_text='Thumbnail or hero image for the service.', upload_to=accounts.models.get_image_upload_path)),
                ('short_description', models.TextField(help_text='A brief summary for service listings.', max_length=300)),
                ('details', models.TextField(help_text='Full, detailed description of the service.')),
                ('category', models.CharField(help_text="Category of the service (e.g., 'Smart Infrastructure', 'Software Development').", max_length=100)),
                ('link', models.URLField(blank=True, help_text='Optional: External URL if this service links elsewhere. Leave blank for internal dynamic links.', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the service appears.')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Name of the person giving the testimony.', max_length=100)),
                ('company_name', models.CharField(blank=True, help_text='Company name of the person giving the testimony.', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Job title or designation of the person.', max_length=100)),
                ('client_role', models.CharField(blank=True, help_text="Their role related to your company (e.g., 'Client', 'Partner').", max_length=100)),
                ('message', models.TextField(help_text='The actual testimony message.')),
                ('rating', models.IntegerField(help_text='Rating out of 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_submitted', models.DateField(default=datetime.date.today, help_text='Date the testimony was given.')),
                ('is_approved', models.BooleanField(default=False, help_text='Check to display this testimony on the website.')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-date_submitted', 'person_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('admin_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='Admin Type')),
                ('is_content_editor', models.BooleanField(default=False, verbose_name='Is Content Editor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'db_table': 'auth_user',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full legal name of the company (e.g., Rovid Smart Technology).', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='Short name or abbreviation (e.g., RovidGH).', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Company logo.', null=True, upload_to=accounts.models.get_image_upload_path)),
                ('tagline', models.CharField(blank=True, help_text='A short, catchy phrase about the company.', max_length=255)),
                ('mission', models.TextField(blank=True, help_text='Company mission statement.')),
                ('vision', models.TextField(blank=True, help_text='Company vision statement.')),
                ('values', models.TextField(blank=True, help_text='Core values of the company.')),
                ('about_us_text', models.TextField(blank=True, help_text="Longer 'About Us' section text.")),
                ('email', models.EmailField(blank=True, help_text='General contact email address.', max_length=254)),
                ('location_description', models.CharField(blank=True, help_text="General location description (e.g., 'Accra, Ghana').", max_length=255)),
                ('mailing_address', models.TextField(blank=True, help_text='Full mailing address.')),
                ('postal_address', models.TextField(blank=True, help_text='Full postal address (if different from mailing).')),
                ('tel', models.CharField(blank=True, help_text='Main telephone number.', max_length=50)),
                ('fax', models.CharField(blank=True, help_text='Fax number.', max_length=50)),
                ('phone1', models.CharField(blank=True, help_text='Primary mobile/contact number.', max_length=50)),
                ('phone2', models.CharField(blank=True, help_text='Secondary mobile/contact number.', max_length=50)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL.', null=True)),
                ('x', models.URLField(blank=True, help_text='X (Twitter) profile URL.', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL.', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL.', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='TikTok profile URL.', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel URL.', null=True)),
                ('github', models.URLField(blank=True, help_text='GitHub profile/organization URL.', null=True)),
                ('google_business_profile', models.URLField(blank=True, help_text='Google Business Profile URL (e.g., Google Maps listing).', null=True)),
                ('yahoo_business_profile', models.URLField(blank=True, help_text='Yahoo Business Profile URL.', null=True)),
                ('copyright_text', models.CharField(blank=True, help_text="Text for the website footer copyright (e.g., '© 2025 Rovid Smart Technology.').", max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Company (Global Settings)',
                'constraints': [models.UniqueConstraint(fields=('id',), name='unique_company_settings')],
            },
        ),
    ]
