# Generated by Django 5.1.2 on 2025-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='values',
            field=models.JSONField(blank=True, help_text='Core values of the company.'),
        ),
    ]
