# Generated by Django 5.2.7 on 2025-11-30 22:55

import datetime
import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Internal title for the carousel slide (e.g., 'Homepage Slide 1')", max_length=100)),
                ('image', models.ImageField(help_text='Background image for the carousel slide.', upload_to=main.models.get_image_upload_path)),
                ('main_text', models.CharField(help_text='The primary headline or main message on the slide.', max_length=255)),
                ('link', models.URLField(blank=True, help_text='Optional: URL this slide links to.', null=True)),
                ('text_1', models.TextField(blank=True, help_text='First line/paragraph of supporting text.')),
                ('text_2', models.TextField(blank=True, help_text='Second line/paragraph of supporting text.')),
                ('icon', models.CharField(blank=True, help_text="Optional: FontAwesome icon class (e.g., 'fa fa-play').", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which the slides appear (lower number first).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is currently active on the website.')),
            ],
            options={
                'verbose_name_plural': 'Carousels',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the client company or individual.', max_length=100, unique=True)),
                ('industry', models.CharField(blank=True, help_text="Industry of the client (e.g., 'Healthcare', 'Tech').", max_length=100)),
                ('client_logo', models.ImageField(help_text='Logo of the client.', upload_to=main.models.get_image_upload_path)),
                ('project_title', models.CharField(blank=True, help_text='Title of a specific project done for this client.', max_length=200)),
                ('project_link', models.URLField(blank=True, help_text='Optional: Link to the detailed project page or case study.', null=True)),
                ('display_on_homepage', models.BooleanField(default=False, help_text='Check to feature this client on the homepage.')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Subject of the message.', max_length=200)),
                ('message', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True, help_text='Date and time when the message was submitted.')),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read after reviewing the message.')),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submission_time'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier for the project URL (auto-generated if left blank).', max_length=220, unique=True)),
                ('client_name', models.CharField(help_text='Name of the client for this project.', max_length=100)),
                ('client_logo', models.ImageField(blank=True, help_text="Optional: Client's logo for this specific project.", null=True, upload_to=main.models.get_image_upload_path)),
                ('description', models.TextField(help_text='Detailed description of the project, including scope and achievements.')),
                ('category', models.CharField(help_text="Main category of the project (e.g., 'Smart Infrastructure', 'Software').", max_length=100)),
                ('type', models.CharField(blank=True, help_text="Type of project (e.g., 'Residential', 'Commercial', 'Web Application').", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Geographical location of the project.', max_length=200)),
                ('completion_date', models.DateField(help_text='Date the project was completed.')),
                ('image1', models.ImageField(blank=True, help_text='Main image for the project.', null=True, upload_to=main.models.get_image_upload_path)),
                ('image2', models.ImageField(blank=True, help_text='Second image for the project.', null=True, upload_to=main.models.get_image_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-completion_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the service (e.g., 'Building Management Systems').", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier for the service URL (auto-generated if left blank).', max_length=120, unique=True)),
                ('image', models.ImageField(help_text='Thumbnail or hero image for the service.', upload_to=main.models.get_image_upload_path)),
                ('short_description', models.TextField(help_text='A brief summary for service listings.', max_length=300)),
                ('details', models.TextField(help_text='Full, detailed description of the service.')),
                ('category', models.CharField(help_text="Category of the service (e.g., 'Smart Infrastructure', 'Software Development').", max_length=100)),
                ('link', models.URLField(blank=True, help_text='Optional: External URL if this service links elsewhere. Leave blank for internal dynamic links.', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the service appears.')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Name of the person giving the testimony.', max_length=100)),
                ('company_name', models.CharField(blank=True, help_text='Company name of the person giving the testimony.', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Job title or designation of the person.', max_length=100)),
                ('client_role', models.CharField(blank=True, help_text="Their role related to your company (e.g., 'Client', 'Partner').", max_length=100)),
                ('message', models.TextField(help_text='The actual testimony message.')),
                ('rating', models.IntegerField(help_text='Rating out of 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_submitted', models.DateField(default=datetime.date.today, help_text='Date the testimony was given.')),
                ('is_approved', models.BooleanField(default=False, help_text='Check to display this testimony on the website.')),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-date_submitted', 'person_name'],
            },
        ),
    ]
