# Generated by Django 5.2.7 on 2025-11-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='service_of_interest',
            field=models.CharField(blank=True, help_text='Optional: Service the sender is interested in.', max_length=100),
        ),
    ]
