# Generated by Django 5.2.7 on 2025-12-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage_service_of_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=False, help_text='Whether this project is visible on the portfolio page.'),
        ),
    ]
